=== uvalib/dlps_scripts-webdocs/html/dlps/public/text/practices/practices.dtd
<!--

  practices.dtd - a simple DTD for documentation of local markup practices

  Greg Murray <gpm2a@virginia.edu>
  Written: 2005-08-09
  Last modified: 2005-08-30

-->

<!-- ============================== -->
<!-- PARAMETER ENTITIES             -->
<!-- ============================== -->

<!ENTITY % a.id "id ID #REQUIRED">

<!-- The 'tei' attribute indicates whether an element or attribute is
defined in TEI or not -->
<!ENTITY % a.tei "tei (yes | no) 'yes'">

<!-- The 'key' attribute can be used for generating indexes of
element/attribute names, technical terms, etc. -->
<!ENTITY % a.key "key CDATA #IMPLIED">

<!-- The 'applies' attribute allows filtering documentation output for
different target audiences; practices, markup examples, etc. can be
flagged as applicable only to keyboarding/encoding vendors, only to
internal staff (post-keyboarding), or both -->
<!ENTITY % a.applies "applies (global | POSTKB | VENDOR) 'global'">

<!ENTITY % m.block "admon | p | list">

<!ENTITY % block "(%m.block; | eg)+">

<!ENTITY % m.phrase "att | char | datatype | emph | filename | gi | hi | kw | lb | ptr | ref | tag | term | usage | val | xpath | xref">

<!ENTITY % phrase "(#PCDATA | %m.phrase;)*">
<!ENTITY % phraseBasic "(#PCDATA | hi)*">

<!ENTITY % inter "(#PCDATA | %m.phrase; | %m.block;)*">


<!-- ============================== -->
<!-- TOP-LEVEL ELEMENT              -->
<!-- ============================== -->

<!-- The top-level element; contains a header and a body -->
<!ELEMENT practices (practicesHeader, practicesDoc)>


<!-- ============================== -->
<!-- HEADER ELEMENTS                -->
<!-- ============================== -->

<!-- Main metadata element; declares the title, author, etc. of the
  documentation, and declares the DTD and/or programs used to enforce the
  markup practices being documented -->
<!ELEMENT practicesHeader (docDesc, enforcementDesc)>

<!-- Document description -->
<!ELEMENT docDesc (title, title?, respStmt+, summary?, revisionDesc?)>

<!-- The title of the documentation -->
<!ELEMENT title (#PCDATA)>
<!ATTLIST title type (main | sub) #REQUIRED>

<!-- Responsibility statement; declares the creators, maintainers, etc. of the documentation -->
<!ELEMENT respStmt ( (resp, name)+ )>

<!-- Declares the role or task for which this person is responsible -->
<!ELEMENT resp (#PCDATA)>

<!-- The name, department, etc. of the person, in any form -->
<!ELEMENT name %phraseBasic;>

<!-- Summary or overview of the document -->
<!ELEMENT summary %block;>

<!-- Declares the changes made to the documentation over time -->
<!ELEMENT revisionDesc (change+)>

<!-- Declares the changes made for a particular version of the documentation -->
<!ELEMENT change (date, respStmt+, changeEntry)>

<!-- The date of this version of the documentation -->
<!ELEMENT date (#PCDATA)>
<!ATTLIST date value CDATA #REQUIRED>

<!-- A description of the changes made in this revision of the documentation -->
<!ELEMENT changeEntry %block;>

<!-- Describes the DTD and QA programs used to enforce the markup practices being documented -->
<!ELEMENT enforcementDesc (dtd, programs)>

<!-- Contains information about the DTD to which the markup practices documentation pertains -->
<!ELEMENT dtd (name, dtdFiles)>

<!-- The file(s) that make up the DTD -->
<!ELEMENT dtdFiles (dtdFile+)>

<!-- Describes a particular DTD file -->
<!ELEMENT dtdFile (filename, description)>
<!ATTLIST dtdFile
	diskPath CDATA #REQUIRED
	url CDATA #IMPLIED>

<!-- The name of a file -->
<!ELEMENT filename (#PCDATA)>

<!-- A brief description of a DTD file or program -->
<!ELEMENT description %phrase;>

<!-- Declares the programs used to enforce the markup practices being documented -->
<!ELEMENT programs (program+)>

<!-- Describes a particular program -->
<!ELEMENT program (filename, description)>
<!ATTLIST program
	id ID #REQUIRED
	language (Perl | shell | XSLT) #REQUIRED
	type (processing | QA) #REQUIRED
	diskPath CDATA #REQUIRED
	url CDATA #IMPLIED>


<!-- ============================== -->
<!-- BODY ELEMENTS                  -->
<!-- ============================== -->

<!-- The body of the document -->
<!ELEMENT practicesDoc (argument?, argument?, practiceGroup+)>

<!-- A group of related markup practices -->
<!ELEMENT practiceGroup (head, argument?, (practiceGroup+ | practice+))>
<!ATTLIST practiceGroup
	%a.id;
	%a.applies;>

<!-- An individual markup practice; this is the central element of any <practices> document -->
<!ELEMENT practice (head, desc, remarks?, exemplum*, enforcement, reason?, exceptions?, seeAlso?, seeAlso?)>
<!ATTLIST practice
	%a.id;
	%a.applies;>

<!-- Summary or overview of the document or a subsection of it -->
<!ELEMENT argument %block;>
<!ATTLIST argument %a.applies;>

<!-- A brief description of the markup practice -->
<!ELEMENT desc %phrase;>

<!-- Describes how the markup practice is machine-enforced (if at all) -->
<!ELEMENT enforcement (remarks?)>
<!ATTLIST enforcement
	machine-enforceable (yes | semi | no) 'yes'
	enforced (yes | no) 'yes'
	method (dtd | program) #IMPLIED
	method-name IDREFS #IMPLIED
	message-type (error | warning | info) #IMPLIED>

<!-- Describes exceptions to the practice -->
<!ELEMENT exceptions %block;>
<!ATTLIST exceptions type (newspapers | manuscripts) #IMPLIED>

<!-- Provides one or more markup examples, with optional description
(or a pointer to a related example) -->
<!ELEMENT exemplum (
  (
    ( (%m.block;)*, eg+, (%m.block;)*, eg* )
  |
    (ptr | ref | xref)+
  )
)>
<!ATTLIST exemplum %a.applies;>

<!-- The main heading for the markup practice -->
<!ELEMENT head %phrase;>

<!-- Describes the reasons for the markup practice -->
<!ELEMENT reason %block;>
<!ATTLIST reason category (delivery) #IMPLIED>

<!-- Additional remarks that supplement the brief description -->
<!ELEMENT remarks %block;>

<!-- Pointers to related practices or groups of practices -->
<!ELEMENT seeAlso (ptr+)>
<!ATTLIST seeAlso %a.applies;>


<!-- ============================== -->
<!-- BLOCK-LEVEL ELEMENTS           -->
<!-- ============================== -->

<!-- An admonition set off from the main text; comparable to <note>,
<tip>, <important>, etc. in DocBook -->
<!ELEMENT admon ( (p | list | eg)+ )>
<!ATTLIST admon type (important | note | tip) #REQUIRED>

<!-- A markup example -->
<!ELEMENT eg %phraseBasic;>
<!ATTLIST eg %a.applies;>

<!-- A group of examples; only used when repeating the same example, one for
each target audience -->
<!ELEMENT egGroup (eg, eg)>

<!-- A list item -->
<!ELEMENT item %inter;>

<!-- The label for a list item -->
<!ELEMENT label %phrase;>

<!-- A list, which can contain either label/item pairs, or just items -->
<!ELEMENT list (head?, ( (label,item)+ | (item+) ) )>

<!-- A paragraph -->
<!ELEMENT p %phrase;>


<!-- ============================== -->
<!-- PHRASE-LEVEL ELEMENTS          -->
<!-- ============================== -->

<!-- Contains the name of an attribute for an XML element -->
<!ELEMENT att (#PCDATA)>
<!ATTLIST att
	%a.tei;
	%a.key;
	element CDATA #IMPLIED>

<!-- Identifies/inserts a symbol or other special character -->
<!ELEMENT char EMPTY >
<!ATTLIST char name (dagger | ldquo | mdash | nbsp | ndash | rdquo | rsquo) #REQUIRED>

<!-- Contains the name of a datatype of some kind, typically an XML attribute
type (ID, IDREF, etc.) -->
<!ELEMENT datatype (#PCDATA)>

<!-- Marks a word or phrase for rhetorical emphasis -->
<!ELEMENT emph %phrase;>

<!-- Contains the name (generic identifier) of an XML element -->
<!ELEMENT gi (#PCDATA)>
<!ATTLIST gi %a.tei; %a.key;>

<!-- Marks a word or phrase as distinct in some way, specified by the required
'rend' attribute; here, the options are to mark a phrase as requiring attention,
as bolded, as italicized, or as revised (new or updated since the last version
of the documentation) -->
<!ELEMENT hi %phrase;>
<!ATTLIST hi rend (attn | bold | italic | revised) #REQUIRED>

<!-- A line break -->
<!ELEMENT lb EMPTY>

<!-- A pointer/cross-reference to another section within the document;
does not specify the text for the link (on the assumption that the processor
(XSLT stylesheet) will supply the heading for the section being pointed to) -->
<!ELEMENT ptr EMPTY>
<!ATTLIST ptr target IDREF #REQUIRED>

<!-- A pointer/cross-reference to another section within the document;
specifies the text for the link -->
<!ELEMENT ref %phrase;>
<!ATTLIST ref target IDREF #REQUIRED>

<!-- Contains a complete start-tag (or, less often, end-tag), possibly including
attribute specifications, but excluding the opening and closing markup delimiter
characters -->
<!ELEMENT tag (#PCDATA)>
<!ATTLIST tag %a.tei; %a.key;>

<!-- Contains a word or short phrase considered a technical term; typically used
when a technical term is introduced or defined -->
<!ELEMENT term (#PCDATA)>
<!ATTLIST term %a.key;>

<!-- Contains a brief, inline usage example, typically a short markup example -->
<!ELEMENT usage (#PCDATA)>
<!ATTLIST usage %a.tei; %a.key; %a.applies;>

<!-- Contains a value of some kind, typically an attribute value -->
<!ELEMENT val (#PCDATA)>
<!ATTLIST val quoted (yes | no) 'yes'>

<!-- Contains an XPath expression -->
<!ELEMENT xpath (#PCDATA)>
<!ATTLIST xpath %a.key;>

<!-- A pointer/cross-reference to an external document or subsection of an
external document -->
<!ELEMENT xref %phrase;>
<!ATTLIST xref
	url CDATA #REQUIRED
	type (external) #IMPLIED
	%a.applies;>

=== uvalib/dlps_scripts-webdocs/html/dlps/public/text/practices/dlpsPractices.xml
<?xml version="1.0"?>
<!DOCTYPE practices SYSTEM "practices.dtd" [

<!ENTITY dlps-bin "/dlps_work/bin/">
<!ENTITY qa-path "/cenrepo/bin/cgi-dl/dlps/xsl/">
<!ENTITY qa-url "http://text.lib.virginia.edu/bin/cgi-dl/dlps/markupQA/">

<!ENTITY reason_date '
<reason category="delivery"><p>Provides a consistent, machine-readable way of
accessing date values. Facilitates delivery, especially as regards the ability
to perform full-text searches for specific dates or date ranges.</p></reason>
'>

<!ENTITY note_id_remarks '
<p>When creating IDs for notes, use a simple, compact,
human-readable scheme. For notes that are already numbered in the
print source, include the number in the ID. Base the ID scheme on the
referencing scheme used in the print source:</p>
<list>
<label>numbered sequentially throughout</label>
<item>If the notes are numbered sequentially throughout the entire
work, use the printed note number, prefixed with <char name="ldquo"/>n<char name="rdquo"/> (short for
<char name="ldquo"/>note<char name="rdquo"/>). For example, <val>n1</val>, <val>n2</val>, <val>n3</val>,
etc.</item>
<label>numbered within each chapter</label>
<item>If the note numbering starts over at 1 in each chapter, create a
unique ID by including the chapter number as well as the note
number. For example, the note IDs for the third chapter would be
<val>n3.1</val>, <val>n3.2</val>, <val>n3.3</val>, etc.</item>
<label>identified on each page</label>
<item>If the note numbers or symbols start over on each page, create a
unique ID by numbering the notes sequentially within each chapter. For
example, if the 35th footnote in chapter VI is indicated by an
asterisk (*), the <att>id</att> would be <val>n6.35</val> and the note
body would be marked: 
<usage applies="VENDOR">&lt;note id="n6.35" place="foot"&gt;&lt;ns&gt;*&lt;/ns&gt;...&lt;/note&gt;</usage>
<usage applies="POSTKB">&lt;note id="n6.35" place="foot"&gt;&lt;seg type="note-symbol"&gt;*&lt;/seg&gt;...&lt;/note&gt;</usage>
</item>
</list>
'>

<!ENTITY note_place_remarks '
<p>The possible values for <att>place</att> are:</p>
<list>
<label><val>end</val></label>
<item>note appears in a separate division containing all the notes for
a given section (endnotes)</item>
<label><val>foot</val></label>
<item>note appears in bottom margin (footnotes)</item>
<label><val>left</val></label>
<item>note appears in left margin (marginal notes)</item>
<label><val>right</val></label>
<item>note appears in right margin (marginal notes)</item>
<label><val>head</val></label>
<item>note appears in top margin; rarely used</item>
<label><val>inline</val></label>
<item>note appears within the main body of the text</item>
<label><val>above</val></label>
<item>note appears between the lines of the main text, above the line
to which it refers; rarely used</item>
<label><val>below</val></label>
<item>note appears between the lines of the main text, below the line
to which it refers; rarely used</item>
</list>
'>

]>
<practices>
<practicesHeader>
<docDesc>
<title type="main">TEI Markup Practices</title>
<title type="sub">Digital Library Production Services (DLPS), University of Virginia Library</title>
<respStmt>
<resp>Maintained by</resp>
<name>Greg Murray (gpm2a <hi rend="italic">at</hi> virginia <hi rend="italic">dot</hi> edu), DLPS</name>
</respStmt>
<summary>
<p>The XML source for this documentation describes the local markup
practices for TEI-encoded electronic texts followed by Digital Library
Production Services (DLPS), University of Virginia Library. It
contains three types of markup practices:</p>
<list>
<item>those applicable only to keyboarding/encoding vendors
(<char name="ldquo"/>vendor<char name="rdquo"/> practices)</item>
<item>those applicable only after a text has been received from a
vendor (<char name="ldquo"/>postkb<char name="rdquo"/> practices)</item>
<item>those applicable to both (<char name="ldquo"/>global<char name="rdquo"/>
practices)</item>
</list>
<p>The documentation is intended to be helpful in three main ways:</p>
<list>
<item>as a set of encoding guidelines for keyboarding/encoding vendors
who produce TEI texts for DLPS</item>
<item>as a reference for DLPS staff when working on QA/correction,
markup enhancement, migration, etc. of TEI texts</item>
<item>as a reference for authors of delivery systems for the digital
library, when creating delivery mechanisms for TEI texts produced by
DLPS</item>
</list>
</summary>
<revisionDesc>
<change>
<date value="2005-08">August 2005</date>
<respStmt>
<resp>author</resp>
<name>Greg Murray, DLPS</name>
</respStmt>
<changeEntry><p>Produced first published version. Documented about 100 markup
practices in 8 main categories and about 30 subcategories.</p></changeEntry>
</change>
<change>
<date value="2006-02-24">February 24, 2006</date>
<respStmt>
<resp>corrector</resp>
<name>Greg Murray, DLPS</name>
</respStmt>
<changeEntry><p>Minor corrections and enhancements to existing practices.</p></changeEntry>
</change>
<change>
<date value="2008-07-01">July 1, 2008</date>
<respStmt>
<resp>corrector</resp>
<name>Greg Murray</name>
</respStmt>
<changeEntry><p>Minor changes and additions.</p></changeEntry>
</change>
</revisionDesc>
</docDesc>
<enforcementDesc>
<dtd>
<name>The DLPS DTD (uva-dl-tei)</name>
<dtdFiles>
<dtdFile diskPath="/cenrepo/dtd/tei/tei-p4/tei2.dtd" url="http://text.lib.virginia.edu/dtd/tei/tei-p4/tei2.dtd">
	<filename>tei2.dtd</filename>
	<description>TEI P4 main (driver) file; all other files in the TEI DTD distribution are also required</description>
</dtdFile>
<dtdFile diskPath="/cenrepo/dtd/tei/uva-dl-tei/uva-dl-tei.ent" url="http://text.lib.virginia.edu/dtd/tei/uva-dl-tei/uva-dl-tei.ent">
	<filename>uva-dl-tei.ent</filename>
	<description>DLPS TEI modification file #1 of 2: entity declarations</description>
</dtdFile>
<dtdFile diskPath="/cenrepo/dtd/tei/uva-dl-tei/uva-dl-tei.dtd" url="http://text.lib.virginia.edu/dtd/tei/uva-dl-tei/uva-dl-tei.dtd">
	<filename>uva-dl-tei.dtd</filename>
	<description>DLPS TEI modification file #2 of 2: element declarations</description>
</dtdFile>
</dtdFiles>
</dtd>
<programs>
<program id="char2ent" language="Perl" type="processing" diskPath="&dlps-bin;char2ent">
	<filename>char2ent</filename>
	<description>Converts super-ASCII characters to standard mnemonic character entities, when available</description>
</program>
<program id="notes_n" language="Perl" type="processing" diskPath="&dlps-bin;notes_n">
	<filename>notes_n</filename>
	<description>Adds or updates the <att>n</att> attribute on <gi>note</gi>, <gi>ref</gi>, and <gi>ptr/</gi> elements.</description>
</program>
<program id="replace_xml_decl" language="Perl" type="processing" diskPath="&dlps-bin;replace_xml_decl">
	<filename>replace_xml_decl</filename>
	<description>Replaces XML declaration</description>
</program>
<program id="qa_dates" language="Perl" type="QA" diskPath="&dlps-bin;qa_dates">
	<filename>qa_dates</filename>
	<description>QA program for standardized date values</description>
</program>
<program id="qa_figures" language="Perl" type="QA" diskPath="&dlps-bin;qa_figures">
	<filename>qa_figures</filename>
	<description>QA program for <gi>figure</gi> elements</description>
</program>
<program id="qa_lib_corr" language="XSLT" type="QA" diskPath="&qa-path;qa_lib_corr.xsl" url="&qa-url;">
	<filename>qa_lib_corr.xsl</filename>
	<description>QA program for corrections, additions, and deletions</description>
</program>
<program id="qa_lib_foreign" language="XSLT" type="QA" diskPath="&qa-path;qa_lib_foreign.xsl" url="&qa-url;">
	<filename>qa_lib_foreign.xsl</filename>
	<description>QA program for foreign phrases and the global <att>lang</att> attribute</description>
</program>
<program id="qa_lib_misc" language="XSLT" type="QA" diskPath="&qa-path;qa_lib_misc.xsl" url="&qa-url;">
	<filename>qa_lib_misc.xsl</filename>
	<description>QA program for miscellaneous requirements not handled by the other qa_lib_* stylesheets</description>
</program>
<program id="qa_lib_notes" language="XSLT" type="QA" diskPath="&qa-path;qa_lib_notes.xsl" url="&qa-url;">
	<filename>qa_lib_notes.xsl</filename>
	<description>QA program for TEI notes and note references</description>
</program>
<program id="qa_lib_structure" language="XSLT" type="QA" diskPath="&qa-path;qa_lib_structure.xsl" url="&qa-url;">
	<filename>qa_lib_structure.xsl</filename>
	<description>QA program for TEI document structure</description>
</program>
<program id="qa_xml" language="Perl" type="QA" diskPath="&dlps-bin;qa_xml">
	<filename>qa_xml</filename>
	<description>QA program for XML features</description>
</program>
</programs>
</enforcementDesc>
</practicesHeader>
<practicesDoc>
<argument applies="VENDOR">
<p>This document describes the text encoding practices for initial
document production (keyboarding) followed by Digital Library
Production Services (DLPS), University of Virginia Library. It is
intended for use by keyboarding vendors when encoding electronic texts
for DLPS.</p>
<admon type="note">
<p>When referring to elements <gi>div1</gi> through
<gi>div7</gi> as a group, the pseudo-tag <gi tei="no">divN</gi> is used <char name="mdash"/>
for example, <char name="ldquo"/>The <att>type</att> attribute is required on <gi tei="no">divN</gi>
elements.<char name="rdquo"/></p>
<!--<p>Sections added or revised since the last major version of this
document are <hi rend="revised">highlighted with a light yellow
background</hi>.</p>-->
</admon>
</argument>
<argument applies="POSTKB">
<p>This document describes the local markup practices for TEI-encoded electronic texts
followed by Digital Library Production Services (DLPS), University of Virginia
Library. It is intended to be helpful in two main ways:</p>
<list>
<item>as a reference for DLPS staff when working on QA/correction, markup
enhancement, migration, etc. of TEI texts</item>
<item>as a reference for authors of delivery systems for the digital library,
when creating delivery mechanisms for TEI texts produced by DLPS</item>
</list>
